import type { Product } from '@/types';

const now = new Date().toISOString();

function product(
  partial: Omit<Product, 'createdAt' | 'updatedAt' | 'description' | 'manufacturer' | 'inStock'> & {
    description?: string;
    manufacturer?: string;
    inStock?: boolean;
  },
): Product {
  return {
    description: partial.description ?? 'Wholesale pharmaceutical product for pharmacies and hospitals.',
    manufacturer: partial.manufacturer ?? 'Tainzay Pharma',
    inStock: partial.inStock ?? true,
    createdAt: now,
    updatedAt: now,
    ...partial,
  };
}

export const MOCK_BEST_SELLING: Product[] = [
  product({
    _id: 'bs-1',
    name: 'Amoxicillin 500mg Capsules',
    slug: 'amoxicillin-500mg',
    category: { _id: 'c1', name: 'Antibiotics', slug: 'antibiotics' },
    image: '/products/placeholder.svg',
    basePrice: 2450,
    wholesaleTiers: [{ minQuantity: 10, price: 1935, discountPercentage: 21 }],
    dosageForm: 'Capsule',
    packSize: '500 mg (100 Capsules)',
    featured: true,
    rating: 4.8,
    reviewCount: 687,
  }),
  product({
    _id: 'bs-2',
    name: 'Paracetamol 500mg Tablets',
    slug: 'paracetamol-500mg',
    category: { _id: 'c2', name: 'Pain Relief', slug: 'pain-relief' },
    image: '/products/placeholder.svg',
    basePrice: 890,
    wholesaleTiers: [{ minQuantity: 20, price: 703, discountPercentage: 21 }],
    dosageForm: 'Tablet',
    packSize: '500 mg (200 Tablets)',
    featured: true,
    rating: 4.6,
    reviewCount: 908,
  }),
  product({
    _id: 'bs-3',
    name: 'Vitamin D3 K2 Softgels',
    slug: 'vitamin-d3-k2',
    category: { _id: 'c3', name: 'Vitamins & Minerals', slug: 'vitamins-minerals' },
    image: '/products/placeholder.svg',
    basePrice: 2490,
    wholesaleTiers: [{ minQuantity: 12, price: 1967, discountPercentage: 21 }],
    dosageForm: 'Softgel',
    packSize: '60 Softgels',
    featured: true,
    rating: 4.7,
    reviewCount: 396,
  }),
  product({
    _id: 'bs-4',
    name: 'Metformin 500mg Tablets',
    slug: 'metformin-500mg',
    category: { _id: 'c4', name: 'Diabetes Care', slug: 'diabetes-care' },
    image: '/products/placeholder.svg',
    basePrice: 1850,
    wholesaleTiers: [{ minQuantity: 15, price: 1462, discountPercentage: 21 }],
    dosageForm: 'Tablet',
    packSize: '500 mg (100 Tablets)',
    featured: true,
    rating: 4.5,
    reviewCount: 104,
  }),
  product({
    _id: 'bs-5',
    name: 'Atorvastatin 20mg Tablets',
    slug: 'atorvastatin-20mg',
    category: { _id: 'c5', name: 'Cardiovascular', slug: 'cardiovascular' },
    image: '/products/placeholder.svg',
    basePrice: 3200,
    wholesaleTiers: [{ minQuantity: 10, price: 2528, discountPercentage: 21 }],
    dosageForm: 'Tablet',
    packSize: '20 mg (30 Tablets)',
    featured: true,
    rating: 4.4,
    reviewCount: 241,
  }),
  product({
    _id: 'bs-6',
    name: 'Omeprazole 20mg Capsules',
    slug: 'omeprazole-20mg',
    category: { _id: 'c6', name: 'Gastrointestinal', slug: 'gastrointestinal' },
    image: '/products/placeholder.svg',
    basePrice: 1450,
    wholesaleTiers: [{ minQuantity: 20, price: 1145, discountPercentage: 21 }],
    dosageForm: 'Capsule',
    packSize: '20 mg (14 Capsules)',
    featured: true,
    rating: 4.6,
    reviewCount: 512,
  }),
  product({
    _id: 'bs-7',
    name: 'Cetirizine 10mg Tablets',
    slug: 'cetirizine-10mg',
    category: { _id: 'c7', name: 'Cold & Flu', slug: 'cold-flu' },
    image: '/products/placeholder.svg',
    basePrice: 650,
    wholesaleTiers: [{ minQuantity: 30, price: 513, discountPercentage: 21 }],
    dosageForm: 'Tablet',
    packSize: '10 mg (30 Tablets)',
    featured: true,
    rating: 4.3,
    reviewCount: 189,
  }),
  product({
    _id: 'bs-8',
    name: 'Azithromycin 500mg Tablets',
    slug: 'azithromycin-500mg',
    category: { _id: 'c1', name: 'Antibiotics', slug: 'antibiotics' },
    image: '/products/placeholder.svg',
    basePrice: 2800,
    wholesaleTiers: [{ minQuantity: 10, price: 2212, discountPercentage: 21 }],
    dosageForm: 'Tablet',
    packSize: '500 mg (6 Tablets)',
    featured: true,
    rating: 4.7,
    reviewCount: 334,
  }),
];

export const MOCK_NEW_ARRIVALS: Product[] = [
  product({
    _id: 'na-1',
    name: 'Multivitamin Complex Forte',
    slug: 'multivitamin-complex-forte',
    category: { _id: 'c3', name: 'Vitamins & Minerals', slug: 'vitamins-minerals' },
    image: '/products/placeholder.svg',
    basePrice: 1800,
    wholesaleTiers: [{ minQuantity: 12, price: 1422, discountPercentage: 21 }],
    dosageForm: 'Tablet',
    packSize: '60 Tablets',
    featured: true,
    rating: 4.2,
    reviewCount: 28,
  }),
  product({
    _id: 'na-2',
    name: 'Ibuprofen 400mg Tablets',
    slug: 'ibuprofen-400mg',
    category: { _id: 'c2', name: 'Pain Relief', slug: 'pain-relief' },
    image: '/products/placeholder.svg',
    basePrice: 980,
    wholesaleTiers: [{ minQuantity: 20, price: 774, discountPercentage: 21 }],
    dosageForm: 'Tablet',
    packSize: '400 mg (100 Tablets)',
    featured: true,
    rating: 4.1,
    reviewCount: 15,
  }),
  product({
    _id: 'na-3',
    name: 'Losartan 50mg Tablets',
    slug: 'losartan-50mg',
    category: { _id: 'c5', name: 'Cardiovascular', slug: 'cardiovascular' },
    image: '/products/placeholder.svg',
    basePrice: 2100,
    wholesaleTiers: [{ minQuantity: 10, price: 1659, discountPercentage: 21 }],
    dosageForm: 'Tablet',
    packSize: '50 mg (28 Tablets)',
    featured: true,
    rating: 4.0,
    reviewCount: 9,
  }),
  product({
    _id: 'na-4',
    name: 'Salbutamol Inhaler 100mcg',
    slug: 'salbutamol-inhaler',
    category: { _id: 'c8', name: 'Respiratory', slug: 'respiratory' },
    image: '/products/placeholder.svg',
    basePrice: 1650,
    wholesaleTiers: [{ minQuantity: 8, price: 1303, discountPercentage: 21 }],
    dosageForm: 'Inhaler',
    packSize: '200 Doses',
    featured: true,
    rating: 4.5,
    reviewCount: 42,
  }),
  product({
    _id: 'na-5',
    name: 'Clotrimazole Cream 1%',
    slug: 'clotrimazole-cream',
    category: { _id: 'c9', name: 'Dermatology', slug: 'dermatology' },
    image: '/products/placeholder.svg',
    basePrice: 720,
    wholesaleTiers: [{ minQuantity: 24, price: 568, discountPercentage: 21 }],
    dosageForm: 'Cream',
    packSize: '20 g Tube',
    featured: true,
    rating: 4.3,
    reviewCount: 61,
  }),
  product({
    _id: 'na-6',
    name: 'Pediatric Syrup Multivitamin',
    slug: 'pediatric-syrup-multivitamin',
    category: { _id: 'c10', name: 'Pediatrics', slug: 'pediatrics' },
    image: '/products/placeholder.svg',
    basePrice: 1350,
    wholesaleTiers: [{ minQuantity: 12, price: 1066, discountPercentage: 21 }],
    dosageForm: 'Syrup',
    packSize: '120 ml',
    featured: true,
    rating: 4.4,
    reviewCount: 37,
  }),
  product({
    _id: 'na-7',
    name: 'Omega-3 Fish Oil Capsules',
    slug: 'omega-3-fish-oil',
    category: { _id: 'c3', name: 'Vitamins & Minerals', slug: 'vitamins-minerals' },
    image: '/products/placeholder.svg',
    basePrice: 2990,
    wholesaleTiers: [{ minQuantity: 10, price: 2362, discountPercentage: 21 }],
    dosageForm: 'Softgel',
    packSize: '60 Softgels',
    featured: true,
    rating: 4.6,
    reviewCount: 18,
  }),
  product({
    _id: 'na-8',
    name: 'Iron + Folic Acid Tablets',
    slug: 'iron-folic-acid',
    category: { _id: 'c11', name: "Women's Health", slug: 'womens-health' },
    image: '/products/placeholder.svg',
    basePrice: 980,
    wholesaleTiers: [{ minQuantity: 20, price: 774, discountPercentage: 21 }],
    dosageForm: 'Tablet',
    packSize: '30 Tablets',
    featured: true,
    rating: 4.2,
    reviewCount: 24,
  }),
];

export const MOCK_OFFERS: Product[] = [
  product({
    _id: 'offer-1',
    name: 'Buy 2 Amoxicillin Get 1 Free',
    slug: 'offer-amoxicillin-bogo',
    description: 'Wholesale bundle: buy 2 packs of Amoxicillin 500mg and get 1 free.',
    category: { _id: 'c1', name: 'Antibiotics', slug: 'antibiotics' },
    image: '/products/placeholder.svg',
    basePrice: 4900,
    wholesaleTiers: [{ minQuantity: 1, price: 3267, discountPercentage: 33 }],
    dosageForm: 'Capsule',
    packSize: 'Buy 2 Get 1 Free',
    featured: true,
    rating: 4.8,
    reviewCount: 289,
  }),
  product({
    _id: 'offer-2',
    name: 'Pain Relief Bulk Pack',
    slug: 'offer-pain-relief-bulk',
    description: 'Paracetamol + Ibuprofen wholesale combo for pharmacies.',
    category: { _id: 'c2', name: 'Pain Relief', slug: 'pain-relief' },
    image: '/products/placeholder.svg',
    basePrice: 2750,
    wholesaleTiers: [{ minQuantity: 1, price: 2172, discountPercentage: 21 }],
    dosageForm: 'Tablet',
    packSize: 'Combo Pack',
    featured: true,
    rating: 4.5,
    reviewCount: 123,
  }),
  product({
    _id: 'offer-3',
    name: 'Immunity Boost Bundle',
    slug: 'offer-immunity-boost',
    description: 'Vitamin D3 K2 + Multivitamin Complex wholesale bundle.',
    category: { _id: 'c3', name: 'Vitamins & Minerals', slug: 'vitamins-minerals' },
    image: '/products/placeholder.svg',
    basePrice: 4290,
    wholesaleTiers: [{ minQuantity: 1, price: 2990, discountPercentage: 30 }],
    dosageForm: 'Softgel + Tablet',
    packSize: '2 Products Bundle',
    featured: true,
    rating: 4.7,
    reviewCount: 156,
  }),
  product({
    _id: 'offer-4',
    name: 'Diabetes Care Duo',
    slug: 'offer-diabetes-care-duo',
    description: 'Metformin + support formula at special wholesale pricing.',
    category: { _id: 'c4', name: 'Diabetes Care', slug: 'diabetes-care' },
    image: '/products/placeholder.svg',
    basePrice: 3700,
    wholesaleTiers: [{ minQuantity: 1, price: 2923, discountPercentage: 21 }],
    dosageForm: 'Tablet',
    packSize: 'Duo Pack',
    featured: true,
    rating: 4.4,
    reviewCount: 97,
  }),
  product({
    _id: 'offer-5',
    name: 'Cold & Flu Season Pack',
    slug: 'offer-cold-flu-pack',
    description: 'Cetirizine + support medicines for seasonal wholesale demand.',
    category: { _id: 'c7', name: 'Cold & Flu', slug: 'cold-flu' },
    image: '/products/placeholder.svg',
    basePrice: 1950,
    wholesaleTiers: [{ minQuantity: 1, price: 1540, discountPercentage: 21 }],
    dosageForm: 'Tablet',
    packSize: 'Season Pack',
    featured: true,
    rating: 4.3,
    reviewCount: 84,
  }),
  product({
    _id: 'offer-6',
    name: 'Heart Health Bundle',
    slug: 'offer-heart-health',
    description: 'Atorvastatin + Losartan wholesale bundle for cardiovascular care.',
    category: { _id: 'c5', name: 'Cardiovascular', slug: 'cardiovascular' },
    image: '/products/placeholder.svg',
    basePrice: 5300,
    wholesaleTiers: [{ minQuantity: 1, price: 4187, discountPercentage: 21 }],
    dosageForm: 'Tablet',
    packSize: '2 Products Bundle',
    featured: true,
    rating: 4.6,
    reviewCount: 112,
  }),
  product({
    _id: 'offer-7',
    name: 'Women Wellness Offer',
    slug: 'offer-women-wellness',
    description: 'Iron + Folic Acid with Multivitamin at discounted wholesale rate.',
    category: { _id: 'c11', name: "Women's Health", slug: 'womens-health' },
    image: '/products/placeholder.svg',
    basePrice: 2780,
    wholesaleTiers: [{ minQuantity: 1, price: 1850, discountPercentage: 33 }],
    dosageForm: 'Tablet',
    packSize: 'Wellness Duo',
    featured: true,
    rating: 4.5,
    reviewCount: 203,
  }),
  product({
    _id: 'offer-8',
    name: 'GI Relief Combo',
    slug: 'offer-gi-relief',
    description: 'Omeprazole wholesale combo for gastrointestinal support.',
    category: { _id: 'c6', name: 'Gastrointestinal', slug: 'gastrointestinal' },
    image: '/products/placeholder.svg',
    basePrice: 2900,
    wholesaleTiers: [{ minQuantity: 1, price: 2291, discountPercentage: 21 }],
    dosageForm: 'Capsule',
    packSize: 'Combo Pack',
    featured: true,
    rating: 4.4,
    reviewCount: 76,
  }),
];

/** Combined list used when API returns featured products or as a general fallback */
export const MOCK_PRODUCTS: Product[] = [...MOCK_BEST_SELLING];
